#!/bin/sh

# xrdp control script
# Written : 1-13-2006 - Mark Balliet - posicat@pobox.com
# maintaned by Jay Sorg
# Author David LECHEVALIER <david@ulteo.com> 2010
# Author Samuel BOVEE <samuel@ulteo.com> 2010-2011
# Author Julien LANGLOIS <julien@ulteo.com> 2013
# chkconfig: 2345 11 89
# description: starts xrdp

### BEGIN INIT INFO
# Provides:          xrdp
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start xrdp daemon
# Description:       Provide rdp support.
### END INIT INFO

SBINDIR=/usr/sbin
CFGDIR=/etc/xrdp
LOGDIR=/var/log/xrdp
SPOOLDIR=/var/spool/xrdp
PIDDIR=/var/run
LOGDIR=/dev/null

BINARIES="xrdp-logd xrdp-printerd xrdp xrdp-sesman"

# Source function library.
. /etc/init.d/functions

for exe in $(for i in $BINARIES; do echo /usr/sbin/$i; done) $CFGDIR/startwm.sh; do
    if ! [ -x "$exe" ]; then
      echo -n "$exe is not executable"
      warning
      echo
      exit 2
    fi
done

xrdp_start()
{
  xrdp-logoff all
  FAILED=0
  for exe in $BINARIES; do
    status -p "$PIDDIR/$exe.pid" $exe >/dev/null 2>&1
    RET=$?
    if [ $RET -ne 1 ] && [ $RET -ne 3 ]; then
      FAILED=1
      echo -n "$exe is already loaded ($RET)"
      warning
      echo
    fi
  done
  if [ $FAILED -eq 1 ]; then
    echo -n "Do not try to launch another daemon !"
    warning
    echo
    exit 1
  fi
  for exe in $BINARIES; do
      echo -n "Starting $exe"
      daemon --pidfile="$PIDDIR/$exe.pid" $SBINDIR/$exe
      echo
  done
}

xrdp_stop()
{
  xrdp-logoff all

  for exe in $(echo $BINARIES | tac -s ' '); do
    echo -n "Stopping $exe"
      killproc -p "$PIDDIR/$exe.pid" $exe -15
    echo
  done;
}


case "$1" in

  start)
    xrdp_start
  ;;

  stop)
    xrdp_stop
  ;;

  force-reload|restart)
    echo "Restarting xrdp..."
    xrdp_stop
    sleep 2
    xrdp_start
  ;;

  status)
    for exe in $BINARIES; do
        status -p "$PIDDIR/$exe.pid" $exe 
    done
  ;;

  *)
    echo "Usage: $0 {start|stop|restart|force-reload|status}"
    exit 2
  ;;

esac

exit $?
