.TH  VCHANNEL_RDPDR 1 "February 04, 2010" "Version 1.0" "XRDP vchannel_rdpdr Manual"
.SH NAME 
vchannel_rdpdr \- an XRDP command...
.SH SYNOPSIS
.B vchannel_rdpdr
[\fB-options\fP|\fB...\fP]
.SH DESCRIPTION
\fBvchannel_rdpdr\fP ...
.SH OPTIONS
The following options are supported:
.SH LICENCE
Copyright (c) 2010 Ulteo SAS 
.br
This software is released under the GNU General Public License. Please
read the COPYING file for more information. 
.SH REPORTING BUGS
Please send a report to <report-ovd-bugs@ulteo.com>
.SH AUTHOR
Written by \fBSamuel Bovée\fP.
